version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webapi
  api:
    image: pantyporowicz/osp-webapp-api:latest
    build: .
    ports:
      - "3000:3000"
    command:
      npm run start
