version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webapi
  api:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: webapi
      RABBIT_HOST: rabbit
    command:
      node start-dev.js
  rabbit:
    image: rabbitmq:3.9-management
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
