name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    container:
      image: docker/compose:1.29.2
    env:
      SERVICE: api
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SERVER_CONNECTION_STRING: ${{ secrets.SERVER_CONNECTION_STRING }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configuration
        run: npm i -g zx
      - name: Build
        run: |
          chmod +x devops/docker-build-and-push.sh
          sh devops/docker-build-and-push.sh
      - name: Deploy
        run: |
          chmod +x devops/deploy.sh
          sh devops/deploy.sh
